---
- name: Install WordPress, MariaDB, Nginx, and PHP-FPM
  hosts: all
  #remote_user: centos
  remote_user: '{{ os_user }}'
  become: yes
  become_user: root

  # remote_user: user
  # sudo: yes

  roles:
    - common
    - mariadb
    - nginx
    - php-fpm
    - wordpress
