---
- name: Install WordPress, MariaDB, Nginx, and PHP-FPM
  hosts: all
  remote_user: centos
  become: yes
  become_user: root

  # remote_user: user
  # sudo: yes
  vars:
    heat_endpoint: "{{ heat_endpoint }}"
    heat_token: "{{ heat_token }}"

  tasks:
    - command echo "{{ heat_endpoint }}"
    - command echo "{{ heat_token }}"

  roles:
    - common
    - mariadb
    - nginx
    - php-fpm
    - wordpress
