---
- name: Install WordPress, MariaDB, Nginx, and PHP-FPM
  hosts: all
  remote_user: centos
  become: yes
  become_user: root

  # remote_user: user
  # sudo: yes
  vars:
    heat_callback_url: "{{ callback }}"

  tasks:
    - command echo "{{ heat_callback_url }}"

  roles:
    - common
    - mariadb
    - nginx
    - php-fpm
    - wordpress
