--- 
- name: "Install WordPress, MariaDB, Nginx, and PHP-FPM"
  become: true
  become_user: root
  hosts: wordpress
  remote_user: cloud-user
  roles: 
    - common
    - mariadb
    - nginx
    - php-fpm
    - wordpress
  vars: 
    heat_endpoint: "{{ HEAT_ENDPOINT|default('foo') }}"
    heat_token: "{{ HEAT_TOKEN|default('foo') }}"
