---
- name: Install WordPress, MariaDB, Nginx, and PHP-FPM
  hosts: all
  remote_user: centos
  become: yes
  become_user: root

  # remote_user: user
  # sudo: yes
  vars:
    heat_endpoint: "{{ HEAT_ENDPOINT|default('foo') }}"
    heat_token: "{{ HEAT_TOKEN|default('foo') }}"

  tasks:
    - name: echo $heat_endpoint
    action: command echo $heat_endpoint

    - name: echo $heat_token
    action: command echo $heat_token

  roles:
    - common
    - mariadb
    - nginx
    - php-fpm
    - wordpress
