---
- block:
  - name: Install nginx
    yum: name=nginx state=present

  - name: Copy nginx configuration for wordpress
    template: src=default.conf dest=/etc/nginx/conf.d/default.conf
    notify: restart nginx

  - name: insert firewalld rule for nginx
    firewalld: port={{ nginx_port }}/tcp permanent=true state=enabled immediate=yes

  - name: http service state
    service: name=nginx state=started enabled=yes
  rescue:
  - name: curl post to Heat to notify of failure
    uri:
      url: "{{ heat_endpoint }}"
      method: POST
      HEADER_X-Auth-Token: "{{ heat_token }}"
      HEADER_Content-Type: "application/json"
      HEADER_Accept: "application/json"
      body: '{"status": "FAILURE"}'
      force_basic_auth: yes
      status_code: 200
      body_format: json

