--- 
- 
  block: 
    - 
      name: "Install MariaDB package"
      with_items: 
        - mariadb-server
        - MySQL-python
        - libselinux-python
        - libsemanage-python
      yum: "name={{ item }} state=installed"
    - 
      name: "Install firewalld"
      with_items: 
        - firewalld
      yum: "name={{ item }} state=installed"
    - 
      name: "Enable firewalld"
      service: "name=firewalld state=started enabled=yes"
    - 
      name: "Configure SELinux to start mysql on any port"
      seboolean: "name=mysql_connect_any state=true persistent=yes"
    - 
      name: "Create Mysql configuration file"
      notify: 
        - "restart mariadb"
      template: "src=my.cnf.j2 dest=/etc/my.cnf"
    - 
      file: "path=/var/log/mysqld.log state=touch owner=mysql group=mysql mode=0775"
      name: "Create MariaDB log file"
    - 
      name: "Start MariaDB Service"
      service: "name=mariadb state=started enabled=yes"
    - 
      firewalld: "port={{ mysql_port }}/tcp permanent=true state=enabled immediate=yes"
      name: "insert firewalld rule"
  rescue: 
    - 
      name: "curl post to Heat to notify of failure"
      uri: 
        HEADER_Accept: application/json
        HEADER_Content-Type: application/json
        HEADER_X-Auth-Token: "{{ heat_token }}"
        body: "{\"status\": \"FAILURE\"}"
        body_format: json
        force_basic_auth: true
        method: POST
        status_code: 200
        url: "{{ heat_endpoint }}"
