---
- name: Install WordPress, MySQL, Nginx, and PHP-FPM
  hosts: all
  remote_user: centos
  become: yes
  become_user: root
  # remote_user: user
  # sudo: yes

  roles:
    - common
    - mysql
    - nginx
    - php-fpm
    - wordpress
